---
- name: add github ssh key
  copy:
    src: "keys/id_rsa"
    dest: /home/ubuntu/.ssh/github_key
    owner: ubuntu
    group: ubuntu
    mode: 0600
# copy GitHub private key to server

- name: configure ssh to use ansible key for github.com
  template:
    src: "config/ssh_config"
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644
# configure ssh to use ansible key for github.com

- name: Clone the project repository
  git:
    repo: git@github.com:COMP90024-G2/COMP90024-project2.git
    key_file: /home/ubuntu/.ssh/github_key
    update: yes
    dest: '{{ remote_working_directory }}'
    force: yes
  environment: "{{ proxy_env }}"
  become: yes

- name: Remove GitHubKey
  file:
    path: /home/ubuntu/.ssh/github_key
    state: absent